### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by hafsamehmood** [SagarBapodara/Coursera-Course-Recommendation-System#1]
Hey, I hope you are fine. I saw your code on recommendation systems and implemented it on my dataset. Results were fine manually, I checked them manually. But you did not evaluate the function, so I wanna ask if someone has to find the precision in terms of percentage, is it possible to do it here and if yes, how will how will we do it? TIA!

**Comment by SagarBapodara** [comment]
Thank you @hafsamehmood. I have not calculated the accuracy or performance metrics for this system. 

To answer your question, it is possible to evaluate the precision/acc of a recommendation system in terms of percentage(s) using metrics like precision@k, recall@k, f1@k, etc. 

However, calculating accuracy is not typically a useful metric for evaluating recommendation models. This is because recommendation systems are made to give personalized predictions for each user based on their preferences, and the ground truth of what a user would actually like or interact with is often unknown. The focus of recommendation systems is on making high-quality recommendations rather than on making predictions that exactly match the ground truth. 

You can find some useful resources here : 

- https://medium.com/@m_n_malaeb/recall-and-precision-at-k-for-recommender-systems-618483226c54

- https://bond-kirill-alexandrovich.medium.com/precision-and-recall-in-recommender-systems-and-some-metrics-stuff-ca2ad385c5f8

- https://towardsdatascience.com/ranking-evaluation-metrics-for-recommender-systems-263d0a66ef54

- https://www.math.uci.edu/icamp/courses/math77b/lecture_12w/pdfs/Chapter%2007%20-%20Evaluating%20recommender%20systems.pdf

I hope this answers your query. If you work on the performance metrics, feel free to include them in this repo for reference.

**Comment by SagarBapodara** [comment]
Since this thread has been inactive, I hope the issue has been resolved.
